Repository schubergphilis/terraform-azure-mcaf-vwan, pull requests merged in 2025-02, with the labels that each got.

#5 enhancement: Add the zones option for the azure firewall
  README.md
  examples/basic/main.tf
  main.tf
  modules/vhub/main.tf
  modules/vhub/variables.tf
  terraform.tf
  variables.tf
Labels: enhancement, feature

#6 enhancement: change name of the proxy, it is a dns proxy to be more precise
  README.md
  examples/basic/main.tf
  modules/vhub/main.tf
  modules/vhub/variables.tf
  variables.tf
Labels: documentation, feature

#7 bug: Restore resource group resource
  README.md
  main.tf
Labels: bug
